"""
FAVOR DE PRIMERO CAMBIAR LAS RUTAS DE LAS VARIBLES DE ESTE ARCHIVO SI ES NECESARIO.
EN EL ARCHIVO "S1_WebScraping_CS" ESTA EL PRIMER MENU.
Y EN EL ARCHIVO "S5_Dashboards_CS" ESTA EL SEGUNDO MENU.
"""

"""
CONSTANTES:
"""

#UBICACION A GUARDAR PARA EL CSV DE WEB SCRAPING. (1ERA ETAPA WS)
data_csv = ("ClaroShop_WebScraping.csv")

#UBICACION A GUARDAR PARA EL CSV RESULTANTE DE LA LIMPIEZA. (2DA ETAPA LD)
data_limpieza = ("ClaroShop_Limpieza.csv")

#CONEXION A MYSQL. (3RA ETAPA CBD)
host = "localhost"
user = "root"
password = "1290"

#UBICACION A GUARDAR PARA EL ARCHIVO CSV RESULTANTE DE SEPARAR SOLO LAS CLASIFICACIONES. (3RA ETAPA CBD)
data_classification = ("ClaroShop_Clasificaciones.csv")

#UBICACION A GUARDAR PARA EL PRIMER QUERY CSV RESULTANTE DE LA CONSULTA A LA BASE DE DATOS. (3RA ETAPA CBD)
data_query1 = ("Query1.csv")

#UBICACION A GUARDAR PARA EL SEGUNDO QUERY CSV RESULTANTE DE LA CONSULTA A LA BASE DE DATOS. (ERA ETAPA CBD)
data_query2 = ("Query2.csv")

